export const Bible = [
  // Old Testament
  {
    bookNumber: 1,
    title: 'Genesis',
    chapters: Array.from({ length: 50 }, (_, i) => i + 1),
    limit: 50,
  },
  {
    bookNumber: 2,
    title: 'Exodus',
    chapters: Array.from({ length: 40 }, (_, i) => i + 1),
    limit: 40,
  },
  {
    bookNumber: 3,
    title: 'Leviticus',
    chapters: Array.from({ length: 27 }, (_, i) => i + 1),
    limit: 27,
  },
  {
    bookNumber: 4,
    title: 'Numbers',
    chapters: Array.from({ length: 36 }, (_, i) => i + 1),
    limit: 36,
  },
  {
    bookNumber: 5,
    title: 'Deuteronomy',
    chapters: Array.from({ length: 34 }, (_, i) => i + 1),
    limit: 34,
  },
  {
    bookNumber: 6,
    title: 'Joshua',
    chapters: Array.from({ length: 24 }, (_, i) => i + 1),
    limit: 24,
  },
  {
    bookNumber: 7,
    title: 'Judges',
    chapters: Array.from({ length: 21 }, (_, i) => i + 1),
    limit: 21,
  },
  {
    bookNumber: 8,
    title: 'Ruth',
    chapters: Array.from({ length: 4 }, (_, i) => i + 1),
    limit: 4,
  },
  {
    bookNumber: 9,
    title: '1 Samuel',
    chapters: Array.from({ length: 31 }, (_, i) => i + 1),
    limit: 31,
  },
  {
    bookNumber: 10,
    title: '2 Samuel',
    chapters: Array.from({ length: 24 }, (_, i) => i + 1),
    limit: 24,
  },
  {
    bookNumber: 11,
    title: '1 Kings',
    chapters: Array.from({ length: 22 }, (_, i) => i + 1),
    limit: 22,
  },
  {
    bookNumber: 12,
    title: '2 Kings',
    chapters: Array.from({ length: 25 }, (_, i) => i + 1),
    limit: 25,
  },
  {
    bookNumber: 13,
    title: '1 Chronicles',
    chapters: Array.from({ length: 29 }, (_, i) => i + 1),
    limit: 29,
  },
  {
    bookNumber: 14,
    title: '2 Chronicles',
    chapters: Array.from({ length: 36 }, (_, i) => i + 1),
    limit: 36,
  },
  {
    bookNumber: 15,
    title: 'Ezra',
    chapters: Array.from({ length: 10 }, (_, i) => i + 1),
    limit: 10,
  },
  {
    bookNumber: 16,
    title: 'Nehemiah',
    chapters: Array.from({ length: 13 }, (_, i) => i + 1),
    limit: 13,
  },
  {
    bookNumber: 17,
    title: 'Esther',
    chapters: Array.from({ length: 10 }, (_, i) => i + 1),
    limit: 10,
  },
  {
    bookNumber: 18,
    title: 'Job',
    chapters: Array.from({ length: 42 }, (_, i) => i + 1),
    limit: 42,
  },
  {
    bookNumber: 19,
    title: 'Psalms',
    chapters: Array.from({ length: 150 }, (_, i) => i + 1),
    limit: 150,
  },
  {
    bookNumber: 20,
    title: 'Proverbs',
    chapters: Array.from({ length: 31 }, (_, i) => i + 1),
    limit: 31,
  },
  {
    bookNumber: 21,
    title: 'Ecclesiastes',
    chapters: Array.from({ length: 12 }, (_, i) => i + 1),
    limit: 12,
  },
  {
    bookNumber: 22,
    title: 'Song of Solomon',
    chapters: Array.from({ length: 8 }, (_, i) => i + 1),
    limit: 8,
  },
  {
    bookNumber: 23,
    title: 'Isaiah',
    chapters: Array.from({ length: 66 }, (_, i) => i + 1),
    limit: 66,
  },
  {
    bookNumber: 24,
    title: 'Jeremiah',
    chapters: Array.from({ length: 52 }, (_, i) => i + 1),
    limit: 52,
  },
  {
    bookNumber: 25,
    title: 'Lamentations',
    chapters: Array.from({ length: 5 }, (_, i) => i + 1),
    limit: 5,
  },
  {
    bookNumber: 26,
    title: 'Ezekiel',
    chapters: Array.from({ length: 48 }, (_, i) => i + 1),
    limit: 48,
  },
  {
    bookNumber: 27,
    title: 'Daniel',
    chapters: Array.from({ length: 12 }, (_, i) => i + 1),
    limit: 12,
  },
  {
    bookNumber: 28,
    title: 'Hosea',
    chapters: Array.from({ length: 14 }, (_, i) => i + 1),
    limit: 14,
  },
  {
    bookNumber: 29,
    title: 'Joel',
    chapters: Array.from({ length: 3 }, (_, i) => i + 1),
    limit: 3,
  },
  {
    bookNumber: 30,
    title: 'Amos',
    chapters: Array.from({ length: 9 }, (_, i) => i + 1),
    limit: 9,
  },
  {
    bookNumber: 31,
    title: 'Obadiah',
    chapters: Array.from({ length: 1 }, (_, i) => i + 1),
    limit: 1,
  },
  {
    bookNumber: 32,
    title: 'Jonah',
    chapters: Array.from({ length: 4 }, (_, i) => i + 1),
    limit: 4,
  },
  {
    bookNumber: 33,
    title: 'Micah',
    chapters: Array.from({ length: 7 }, (_, i) => i + 1),
    limit: 7,
  },
  {
    bookNumber: 34,
    title: 'Nahum',
    chapters: Array.from({ length: 3 }, (_, i) => i + 1),
    limit: 3,
  },
  {
    bookNumber: 35,
    title: 'Habakkuk',
    chapters: Array.from({ length: 3 }, (_, i) => i + 1),
    limit: 3,
  },
  {
    bookNumber: 36,
    title: 'Zephaniah',
    chapters: Array.from({ length: 3 }, (_, i) => i + 1),
    limit: 3,
  },
  {
    bookNumber: 37,
    title: 'Haggai',
    chapters: Array.from({ length: 2 }, (_, i) => i + 1),
    limit: 2,
  },
  {
    bookNumber: 38,
    title: 'Zechariah',
    chapters: Array.from({ length: 14 }, (_, i) => i + 1),
    limit: 14,
  },
  {
    bookNumber: 39,
    title: 'Malachi',
    chapters: Array.from({ length: 4 }, (_, i) => i + 1),
    limit: 4,
  },

  // New Testament
  {
    bookNumber: 40,
    title: 'Matthew',
    chapters: Array.from({ length: 28 }, (_, i) => i + 1),
    limit: 28,
  },
  {
    bookNumber: 41,
    title: 'Mark',
    chapters: Array.from({ length: 16 }, (_, i) => i + 1),
    limit: 16,
  },
  {
    bookNumber: 42,
    title: 'Luke',
    chapters: Array.from({ length: 24 }, (_, i) => i + 1),
    limit: 24,
  },
  {
    bookNumber: 43,
    title: 'John',
    chapters: Array.from({ length: 21 }, (_, i) => i + 1),
    limit: 21,
  },
  {
    bookNumber: 44,
    title: 'Acts',
    chapters: Array.from({ length: 28 }, (_, i) => i + 1),
    limit: 28,
  },
  {
    bookNumber: '45',
    title: 'Romans',
    chapters: Array.from({ length: 16 }, (_, i) => i + 1),
    limit: 16,
  },
  {
    bookNumber: 46,
    title: '1 Corinthians',
    chapters: Array.from({ length: 16 }, (_, i) => i + 1),
    limit: 16,
  },
  {
    bookNumber: 47,
    title: '2 Corinthians',
    chapters: Array.from({ length: 13 }, (_, i) => i + 1),
    limit: 13,
  },
  {
    bookNumber: 48,
    title: 'Galatians',
    chapters: Array.from({ length: 6 }, (_, i) => i + 1),
    limit: 6,
  },
  {
    bookNumber: 49,
    title: 'Ephesians',
    chapters: Array.from({ length: 6 }, (_, i) => i + 1),
    limit: 6,
  },
  {
    bookNumber: 50,
    title: 'Philippians',
    chapters: Array.from({ length: 4 }, (_, i) => i + 1),
    limit: 4,
  },
  {
    bookNumber: 51,
    title: 'Colossians',
    chapters: Array.from({ length: 4 }, (_, i) => i + 1),
    limit: 4,
  },
  {
    bookNumber: 52,
    title: '1 Thessalonians',
    chapters: Array.from({ length: 5 }, (_, i) => i + 1),
    limit: 5,
  },
  {
    bookNumber: 53,
    title: '2 Thessalonians',
    chapters: Array.from({ length: 3 }, (_, i) => i + 1),
    limit: 3,
  },
  {
    bookNumber: 54,
    title: '1 Timothy',
    chapters: Array.from({ length: 6 }, (_, i) => i + 1),
    limit: 6,
  },
  {
    bookNumber: 55,
    title: '2 Timothy',
    chapters: Array.from({ length: 4 }, (_, i) => i + 1),
    limit: 4,
  },
  {
    bookNumber: 56,
    title: 'Titus',
    chapters: Array.from({ length: 3 }, (_, i) => i + 1),
    limit: 3,
  },
  {
    bookNumber: 57,
    title: 'Philemon',
    chapters: Array.from({ length: 1 }, (_, i) => i + 1),
    limit: 1,
  },
  {
    bookNumber: 58,
    title: 'Hebrews',
    chapters: Array.from({ length: 13 }, (_, i) => i + 1),
    limit: 13,
  },
  {
    bookNumber: 59,
    title: 'James',
    chapters: Array.from({ length: 5 }, (_, i) => i + 1),
    limit: 5,
  },
  {
    bookNumber: 60,
    title: '1 Peter',
    chapters: Array.from({ length: 5 }, (_, i) => i + 1),
    limit: 5,
  },
  {
    bookNumber: 61,
    title: '2 Peter',
    chapters: Array.from({ length: 3 }, (_, i) => i + 1),
    limit: 3,
  },
  {
    bookNumber: 62,
    title: '1 John',
    chapters: Array.from({ length: 5 }, (_, i) => i + 1),
    limit: 5,
  },
  {
    bookNumber: 63,
    title: '2 John',
    chapters: Array.from({ length: 1 }, (_, i) => i + 1),
    limit: 1,
  },
  {
    bookNumber: 64,
    title: '3 John',
    chapters: Array.from({ length: 1 }, (_, i) => i + 1),
    limit: 1,
  },
  {
    bookNumber: 65,
    title: 'Jude',
    chapters: Array.from({ length: 1 }, (_, i) => i + 1),
    limit: 1,
  },
  {
    bookNumber: 66,
    title: 'Revelation',
    chapters: Array.from({ length: 22 }, (_, i) => i + 1),
    limit: 22,
  },
];
