export const bookAbbreviations = {
    // Old Testament
    'ps': 'Psalms',
    'psa': 'Psalms',
    'prov': 'Proverbs',
    'pro': 'Proverbs',
    'gen': 'Genesis',
    'gene': 'Genesis',
    'exod': 'Exodus',
    'exo': 'Exodus',
    'lev': 'Leviticus',
    'levi': 'Leviticus',
    'num': 'Numbers',
    'numb': 'Numbers',
    'deut': 'Deuteronomy',
    'deu': 'Deuteronomy',
    'de': 'Deuteronomy',
    'josh': 'Joshua',
    'judg': 'Judges',
    'ruth': 'Ruth',
    'rut': 'Ruth',
    '1sam': '1 Samuel',
    '2sam': '2 Samuel',
    '1kings': '1 Kings',
    '2kings': '2 Kings',
    '1kin': '1 Kings',
    '2kin': '2 Kings',
    '1chron': '1 Chronicles',
    '2chron': '2 Chronicles',
    '1chro': '1 Chronicles',
    '2chro': '2 Chronicles',
    'ezra': 'Ezra',
    'ezr': 'Ezra',
    'neh': 'Nehemiah',
    'esth': 'Esther',
    'job': 'Job',
    'eccl': 'Ecclesiastes',
    'song': 'Song of Solomon',
    'isa': 'Isaiah',
    'is': 'Isaiah',
    'jer': 'Jeremiah',
    'lam': 'Lamentations',
    'ezek': 'Ezekiel',
    'eze': 'Ezekiel',
    'dan': 'Daniel',
    'hos': 'Hosea',
    'joel': 'Joel',
    'joe': 'Joel',
    'amos': 'Amos',
    'amo': 'Amos',
    'obad': 'Obadiah',
    'oba': 'Obadiah',
    'jona': 'Jonah',
    'jonah': 'Jonah',
    'mic': 'Micah',
    'mica': 'Micah',
    'nahum': 'Nahum',
    'nah': 'Nahum',
    'hab': 'Habakkuk',
    'haba': 'Habakkuk',
    'zeph': 'Zephaniah',
    'zep': 'Zephaniah',
    'hag': 'Haggai',
    'zech': 'Zechariah',
    'zec': 'Zechariah',
    'zac': 'Zechariah',
    'mal': 'Malachi',
    'mala': 'Malachi',

    // New Testament
    'mat': 'Matthew',
    'matt': 'Matthew',
    'mark': 'Mark',
    'mar': 'Mark',
    'luke': 'Luke',
    'acts': 'Acts',
    'act': 'Acts',
    'rom': 'Romans',
    '1cor': '1 Corinthians',
    '2cor': '2 Corinthians',
    'gal': 'Galatians',
    'eph': 'Ephesians',
    'ephe': 'Ephesians',
    'phil': 'Philippians',
    'phili': 'Philippians',
    'col': 'Colossians',

   
    'tit': 'Titus',
    'philem': 'Philemon',
    'phile': 'Philemon',
    'heb': 'Hebrews',
    'james': 'James',
    'jam': 'James',
    'john': 'John',
    'joh': 'John',
    '1john': '1 John',
    '2john': '2 John',
    '3john': '3 John',
    'jude': 'Jude',
    'rev': 'Revelation',

    // Adding variations with spaces
    '1joh': '1 John',
    '2joh': '2 John',
    '3joh': '3 John',
    '1 cor': '1 Corinthians',
    '1thess': '1 Thessalonians',
    '2thess': '2 Thessalonians',
    '1thes': '1 Thessalonians',
    '2thes': '2 Thessalonians',
    '2 cor': '2 Corinthians',
    '1tim': '1 Timothy',
    '2tim': '2 Timothy',
    '1timo': '1 Timothy',
    '2timo': '2 Timothy',
    '1pet': '1 Peter',
    '2pet': '2 Peter',
    '1pete': '1 Peter',
    '2pete': '2 Peter',
    'lu': 'Luke',
    'luk': 'Luke'
};